[project]
name = "call-my-agent"
version = "0.1.0"
description = "An AI writer's room built with Python and Azure Semantic Kernel"
readme = "README.md"

dependencies = [
    "semantic-kernel",
    "python-dotenv",
    "openai",
    "requests",
    "reportlab"
]
